apiVersion: "v1"
kind: "Service"
metadata:
  name: "victor-poc-gke-service"
  namespace: "default"
  labels:
    app: "victor-poc-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 8080 
    targetPort: 8080
  selector:
    app: "victor-poc-gke"
  type: "LoadBalancer"
  loadBalancerIP: ""