apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-victor-gke-deployment
  labels:
    app: poc-victor-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-victor-gke 
  template:
    metadata:
      labels:
        app: poc-victor-gke 
    spec:
      containers:
      - name: poc-victor-gke
        image: gcr.io/poc-identificacao/poc-victor-gke
        ports:
        - containerPort: 8080
