apiVersion: "v1"
kind: "Service"
metadata:
  name: "poc-victor-gke-deployment-service"
  namespace: "default"
  labels:
    app: "poc-victor-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "poc-victor-gke"
  type: "LoadBalancer"
  loadBalancerIP: ""